### ISSUE TITLE
Convert markdown to org-mode

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xclojure#100]
The other Lisp tracks have been moving docs to org-mode, as discussed on Gitter some time ago it would be cool if xclojure followed suit... I'll send a PR shortly. Let me know if objections, @kytrinyx @yurrriq @rubysolo

**Comment by yurrriq** [comment]
I love org-mode.

**Comment by canweriotnow** [comment]
@yurrriq - pandoc makes the conversion so much easier... I did it all by hand last time, ugh.

PR is [here](https://github.com/exercism/xclojure/pull/101), if you want to ensure it looks right you can see the github html representation on my branch [here](https://github.com/canweriotnow/xclojure/tree/100_convert_org)

**Comment by yurrriq** [comment]
Nice. Pandoc is awesome. The only thing I might change at first glance is to replace the `**`s with `*`, but I think Org is smart enough that it doesn't matter. It might be cool to and languages to src blocks if that's appropriate anywhere.
