### ISSUE TITLE
Make yurrriq a mentor again

### ISSUE THREAD

**Issue by yurrriq** [exercism/xclojure#104]
Hey @kytrinyx, I noticed I'm no longer a Clojure mentor. Can we fix that? Since I'm basically maintaining this track at the moment, I figure I should probably be a mentor. :smile:

**Comment by yurrriq** [comment]
PS I just reviewed 20~30 Clojure submissions :grin:. Did individual nit stats go away?

**Comment by kytrinyx** [comment]
I fixed the mentor thing for you. Right now you're a mentor in clojure, lfe, and elisp. Want any of the other lisp-y languages while we're at it?

I took out the individual nit stats, yeah. I originally added it thinking it would be an encouragement for providing feedback, but it doesn't seem like it really moved the needle at all.

**Comment by yurrriq** [comment]
I think for the other favors I ought to do the exercises first and they're in good hands anyway. Cheers!

**Comment by kytrinyx** [comment]
OK, cool. In that case: closing this.
