### ISSUE TITLE
Fix robot-name test suite false positive when using atoms.

### ISSUE THREAD

**Issue by dkinzer** [exercism/xclojure#114]
The following code passes current tests for the robot-name exercise on my computer:

```clojure
(ns robot-name)

(defn robot []
  (atom {:name "KIN123"}))

(defn robot-name [robot]
  (@robot :name))

(defn reset-name [robot]
  (swap! robot (fn [m] (assoc m :name "KIN125"))))
```

**Comment by yurrriq** [comment]
The `robot-name-test` is flawed because `(robot-name/reset-name robbie)` should not be evaluated at the top level.

**Comment by yurrriq** [comment]
Thank you raising this issue. I didn't mean to be overly terse. I'm at work. :smile:
