### ISSUE TITLE
Link broken on Clojure page of exercism.io

### ISSUE THREAD

**Issue by BobWhitelock** [exercism/xclojure#118]
Hi - I noticed the link to `ABOUT.md` is broken [here](http://exercism.io/languages/clojure), presumably as this file has recently been changed to `ABOUT.org`.

**Comment by yurrriq** [comment]
@kytrinyx, does `docs/*` need to be in Markdown format? If so, this is a problem across a couple other lisp tracks too. Thanks for raising the issue, @BobWhitelock.

**Comment by kytrinyx** [comment]
No, we parse and render orgmode files just fine.

This is a bug in the exercism/exercism.io repository; I forgot to check what the file names actually are when linking to them on the site.

[update] After investigating this, it appears that exercism/exercism.io doesn't have the necessary information to link to the correct file. I've got plans to rework this to simplify it, but in the meanwhile I'll add a hack to handle it.
