### ISSUE TITLE
Project structure for newcomers

### ISSUE THREAD

**Issue by tejasbubane** [exercism/xclojure#121]
I am pretty new the clojure and just submitted the `hello-world`. The `running the tests` section on [language page](http://exercism.io/languages/clojure) does not mention where to put my solution file, so initially I assumed it would be the problem directory itself. This gave me the error:

```
Could not locate hello_world__init.class or hello_world.clj on classpath
```

So I finally put it inside `test/` assuming it is the tests that require the file and tests ran successfully. Later found out that `exercism-clojure` uses to the `"real-world project structure"` here https://github.com/exercism/xclojure/issues/84.

I think the directory structure should be mentioned in `running the tests` section. Also if possible, creating an empty file inside `src` directory would help, so that people know the source code goes there.

**Comment by yurrriq** [comment]
Hey, thanks for the feedback! I can see how that could be confusing to newcomers.

Would be willing to submit a PR with "stub" solution files?

**Comment by kevgathuku** [comment]
Hey @tejasbubane @yurrriq Thanks for your work on this.
Would it make sense to add the stub files for each exercise, or to make them a requirement when adding a new exercise? 
It would make the whole thing more consistent, rather than some exercises having it and others not having it.
I could add them if needed.

**Comment by canweriotnow** [comment]
@kevgathuku @tejasbubane @yurrriq I think making stub solution files mandatory for all tracks - esp. using "real-world" leiningen projects - is a must-have. On the xscheme and xelisp tracks we always provide stub files to make sure the exercist has the proper requires/includes and file format (esp. for elisp so flycheck doesn't have a conniption)... having a stub file with the ns macro declaration and any necessary requires makes complete sense. I'd be happy to create and self-assign an issue to take this on if desired.

**Comment by yurrriq** [comment]
Sounds good to me then.
