### ISSUE TITLE
Unclear README.md for POV exercise

### ISSUE THREAD

**Issue by object88** [exercism/xclojure#134]
I hope this is the right place to post; if not, please forgive me and point me in the right direction.

The documentation for the POV exercise states that you can start off with a graph,

```
          0
          |
    1-----2-----3
    |     |     |
  4-+-5 6-+-7 8-+-9
```

and re-arrange it from `6`'s perspective, arriving at,

```
        6
        |
  7-----+-----2
              |
        1-----0-----3
        |           |
      4-+-5       8-+-9
```

The claim is that it's easy to see the path from 6 to 9, which is `6 2 0 3 9`.  However, in the initial graph, you don't have to go through the `0` node at all: you could go via `6 2 3 9`.

Is the documentation wrong in how the graph is rearranged?  Or am I missing some part or intent of the exercise?

**Comment by yurrriq** [comment]
IIRC the READMEs are exercism-wide and live in exercism/x-common.

**Comment by yurrriq** [comment]
Looks like the error has been present throughout its life on Exercism. If I'm not mistaken, the original problem from which it was adapted is here: http://www.4clojure.com/problem/130

Feel free to submit a PR to x-common to correct the discrepancy. Thanks for spotting it!

**Comment by petertseng** [comment]
It's not possible to go from 2 to 3; they are both children of 0.

So the problem is that the READMe draws them deceptively (as if there is an edge between 2 and 3, when there is not.)

**Comment by petertseng** [comment]
I infer (from the rearranged graph) that in the original graph, 2 and 3 are both children of 0. In that case, it would not be possible to go from 2 to 3.

The README drew them deceptively, as if 2 was the only child of 0 and 1 and 3 are children of 2.

**Comment by petertseng** [comment]
The README is being terribly inconsistent.

In the top graph: 1, 2, 3 are all children of 0.

In the bottom graph: Only 0 is a child of 2, and 1 and 3 are children of 2.

The bad part? The **same ascii art** is used to draw these two situations. No wonder it is confusing.

**Comment by yurrriq** [comment]
Feel free to re-open this if you're not satisfied, @object88, but I believe exercism/x-common#378 addressed this issue.

**Comment by object88** [comment]
This does help, thanks!
