### ISSUE TITLE
largest_series_product is weird

### ISSUE THREAD

**Issue by alexkalderimis** [exercism/xclojure#49]
The expected values are very strange - `1` when no groups of a sufficient size can be produced, but `0` is a valid value. The strangeness of a sentinel value of `1` means that the obvious solution (below) does not pass the tests:

```clj
(defn largest-product [size input]
  (->> (map (zipmap "0123456789" (range)) input)
          (partition size 1)
          (map #(apply * %))
          (reduce max 0)))
```

Since you have to test if the input to reduce is empty, but cannot seed it with `1`. This extra (and pointless) complexity suggests that the task itself could do with improvement.

**Comment by kytrinyx** [comment]
The identify of multiplication is 1: http://en.wikipedia.org/wiki/Identity_element
Multiplying by zero is still valid.

**Comment by alexkalderimis** [comment]
It is not the zero that is the issue, but the fact that an empty set of runs is meant to produce a result of `1`. This doesn't have anything to do with multiplication, but the handling of an empty sequence.

**Comment by kytrinyx** [comment]
I would think that this has everything to do with multiplication, since the problem is about multiplying numbers.

@exercism/track-maintainers Thoughts?

**Comment by etrepum** [comment]
I agree with @kytrinyx, when the product of an empty list is defined to be a number, it should naturally be 1.

**Comment by pminten** [comment]
Also agreed. This pattern/question comes up a lot actually, such as "what's the result of 'all elements of list X are true' if X is empty?"

In Haskell at least the rule seems to be "if it can be expressed as a repeated application of a binary function and has an identity element (i.e. it's a monoid) then the identity element is the result of passing in the empty list". This makes quite a lot of sense mathematically and I would advocate using this logic whenever the problem pops up in exercism.

**Comment by alexkalderimis** [comment]
OK, I feel I'm going a bit mad here, so forgive the effort, but this really isn't a problem with multiplication, but with `max` .

The problem guarantees that we will never multiply empty lists (short groups are ignored), and the question isn't "how to I multiply an empty list?" (obviously return `1` - that is clear), but "what is the maximum of an empty list?". ie. there are two reductions here, and it is the second (the `max` one) that is annoying and counter-intuitive.

In terms of reduction under multiplication, `*` handles this implicitly, since with no arguments it returns the multiplicative identity. `max` has no identity, and thus requires a minimum for this problem. The minimum chosen for an empty set of groups (*not* and empty group), is `1`, whereas the minimum which passes the tests for a non-empty set of groups is `0`. This is the inconsistency I was talking about.

`*` and its identity is a complete red-herring.

**Comment by chezwicker** [comment]
I have to say that I would expect `null` in lanuages that don't have primitive types or allow `null` where primitive types are returned. I other languages I would either expect an exception to be thrown, or `-1` to be returned if we want to treat the input as invalid. If not, I would expect `0` - mathematically, I would assume non-existence to be closer to `zero` than `identity`.

**Comment by alexkalderimis** [comment]
To make it crystal clear what the problem is, here is some code that makes it clear that the second reduction is weird.

```clj
(defn largest-product [size input]
  (->> (map (zipmap "0123456789" (range)) input)
          (partition size 1)         ;; Empty list when size = 3 and input = "12"
          (map #(reduce  * %)) ;; <-- this reduction is fine.
          (reduce max (if (>= size (count input)) 0 1)))) ;; <-- Different minima for different input
```

**Comment by pminten** [comment]
Quick overview of several tracks, what they return when the size for largest-product is 0:

* perl5, go: returns 1
* javascript: returns 0
* ruby: returns nil
* elixir, python, haskell: throw exception

Note that the behavior of elixir, python and haskell comes from their respective standard libraries, these tracks all use the stdlib max function. Ruby also uses an stdlib function but a different one, it first sorts an array and then calls `Array#last`, which returns nil if no element can be found. Perl5, go and javascript use a custom loop to determine the max and explicitly set the default value.

I would say that `length > 0` is a precondition of the function and that the code should simply never be called this way. In other words: "undefined behavior".

**Comment by kytrinyx** [comment]
I would agree with _undefined behavior_: the function should likely raise/return an exception/error (depending on the language).
