### ISSUE TITLE
Anagram kata example.clj does not pass all the tests in anagram_test.clj

### ISSUE THREAD

**Issue by DeathRay1977** [exercism/xclojure#60]
Hi,

The example.clj does not pass all the tests in anagram_test.clj. In particular, the last test that the Uppercase version of a word is not an anagram of the lowercase version. 

(deftest capital-word-is-not-own-anagram
  (is (= [] (anagram/anagrams-for "BANANA" ["banana"]))))

Whilst I would argue that, in the real world BANANA would be an anagram of banana, in the spirit of the programming exercise and the specification given, I would propose a fix such that the code be refactored to add a test that the word is not an uppercase version of itself. Something like the gist linked to here.

https://gist.github.com/DeathRay1977/e312c5c9f51691e3ad88

If this is an agreeable solution, I will submit a pull request and fix it.

**Comment by kytrinyx** [comment]
As far as I've been able to discern, case is irrelevant, and so BANANA is not an anagram of banana--it's the same word. @canweriotnow what do you think?

**Comment by DeathRay1977** [comment]
The example code works fine in the case where "banana" is not an anagram of "banana". E.G. You get back an empty vector. It fails on the case where "BANANA" is not an anagram of "banana". 

lein test anagram

lein test anagram-test

lein test :only anagram-test/capital-word-is-not-own-anagram

FAIL in (capital-word-is-not-own-anagram) (anagram_test.clj:33)
expected: (= [] (anagram/anagrams-for "BANANA" ["banana"]))
  actual: (not (= [] ["banana"]))

Ran 9 tests containing 9 assertions.
1 failures, 0 errors.
Tests failed.

**Comment by kytrinyx** [comment]
Ah, right. Yeah, I think the example should be changed, rather than the test suite.

**Comment by achengs** [comment]
(Oops. Wondering if that should have been a pull request for review. Didn't mean to take it all the way in one go. Feel free to let me know if that wasn't the way to go.)

**Comment by DeathRay1977** [comment]
Looks good to me. :+1:

**Comment by achengs** [comment]
Yay peer review! Thanks for discovering the issue and for taking a look!
