### ISSUE TITLE
Update Clojure dep to "1.7.0"

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xclojure#61]
Now that 1.7.0 is out of beta/RC status, we should update the project.clj dependencies to 1.7.0, making sure all tests still pass, of course.

**Comment by kytrinyx** [comment]
+1

**Comment by canweriotnow** [comment]
Is it sick that I'll probably do this with a recursive `grep`, `sed`, and `awk`?

**Comment by canweriotnow** [comment]
Also, 1.8.0-alpha2 is out, so all the more reason to get on the 1.7 :train:

**Comment by kytrinyx** [comment]
> Is it sick that I'll probably do this with a recursive grep, sed, and awk?

No, that's how I'd do it.

**Comment by canweriotnow** [comment]
@kytrinyx no grep or awk, I forgot how much simpler xargs makes it - `find . -maxdepth 1 -name project.clj -print0 |xargs -0 sed -i '' 's/clojure "1.6.0"/clojure "1.7.0"/g'`

**Comment by kytrinyx** [comment]
Nice!
