### ISSUE TITLE
Set up Travis tests

### ISSUE THREAD

**Issue by yurrriq** [exercism/xclojure#64]
> Why do the tests use `load-file`?

In my opinion, it's a bad practice and it caused all sorts of headaches when I was setting up track-level testing locally.

**Comment by kytrinyx** [comment]
I think this track was originally written by a not-quite-yet-clojure dev who used it as an experiment in learning clojure. In other words: it probably just happened that way when they shook the internet and a tutorial with load-file fell out.

**Comment by yurrriq** [comment]
:laughing: great description. In [my solutions repo][1], I [modified the test logic][2] a bit to enable [Travis builds][3]. The key change (other than removing all the `load-file` calls) was in this ([later refined][4]) delightfully hackish [`project.clj`][5].

```clojure
(let [paths (-> (:out (clojure.java.shell/sh "ls"))
                (clojure.string/split #"\n")
                (->> (remove #{"README.org" "project.clj" "target"
                               ;; Removed until solved
                               "prime-factors"}))
                vec)]
  (defproject xclojure "0.1.0"
    :description  "Exercism Exercises in Clojure"
    :url          "https://github.com/yurrriq/exercism/tree/clojure"
    :source-paths ~paths
    :test-paths   ~paths
    :dependencies [[org.clojure/clojure    "1.7.0"]
                   [org.clojure/core.typed "0.3.11"]]))
```

In [xclojure][6] we could/should probably parse [`config.json`][7] in place of the `ls` hack.

[1]: https://github.com/yurrriq/exercism
[2]: https://github.com/yurrriq/exercism/commit/7a098e3ad53fb426e76a085cc3b1f2eb7a948da1
[3]: https://travis-ci.org/yurrriq/exercism/builds
[4]: https://github.com/yurrriq/exercism/commit/d9b68e7ca56d15ed525d80280e125d433322c9d2
[5]: https://github.com/yurrriq/exercism/blob/d9b68e7ca56d15ed525d80280e125d433322c9d2/project.clj
[6]: https://github.com/exercism/xclojure
[7]: https://github.com/exercism/xclojure/blob/master/config.json

**Comment by yurrriq** [comment]
Can I be added to this group?

**Comment by yurrriq** [comment]
@kytrinyx, can I have write privileges on this repo? Clojure is probably my strongest language at the moment, so I could be good a resource here going forward too. I have a branch locally and just failed to push it. I guess I though xclojure would be managed by the lisp team, oops.

```bash
$ git push -u origin travis-tests
ERROR: Permission to exercism/xclojure.git denied to yurrriq.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by yurrriq** [comment]
Gonna think on this some more. @canweriotnow, I know you're swamped, but maybe you can take a took. I'm at a bit of a loss for now..

**Comment by kytrinyx** [comment]
@yurrriq I thought you did have write-access to this repo. Verifying now!

**Comment by kytrinyx** [comment]
Update: The lisp team didn't have access to this repo. That's fixed now.

**Comment by yurrriq** [comment]
Thanks! I sincerely hope people didn't get a million Travis emails while I was experimenting.. If so, I'm sorry.

**Comment by kytrinyx** [comment]
I didn't get any emails--it's probably fine.

**Comment by yurrriq** [comment]
:tada:
