### ISSUE TITLE
Nucleotide Count Exception

### ISSUE THREAD

**Issue by timothyrenner** [exercism/xclojure#70]
In the nucleotide exercise the invalid nucleotide test expects an Exception rather than an AssertionError. Is there a reason for this? It felt odd to use interop to solve the test when a `{:pre ...}` or `assert` would suffice.

I'd be happy to PR it, I just think it's worth discussing a bit first, given I'm new-ish to Clojure.

**Comment by yurrriq** [comment]
This issue has come up several times. Feel free to make a PR and we'll review it.

**Comment by timothyrenner** [comment]
PR is at exercism/xclojure#71.
