### ISSUE TITLE
Switch to real-world project structure

### ISSUE THREAD

**Issue by yurrriq** [exercism/xclojure#84]
**Update**:
Since two people who aren't my support this and no one has yet opposed, I've reworded it from a question to a call to action and a to-do list.

In [xlfe][], we opted to use a "real-world" directory structure for the exercises and I think there are great benefits to users in doing so. Right now, xclojure uses `:{source,test}-paths [""]` to allow users to ignore convention and get coding right away.

I think that's a bad idea. See the output below for my proposed changes.

N.B. I'm pretty sure some documentation would have to be updated accordingly, too.

[xlfe]: https://github.com/exercism/xlfe

```
bob
├── project.clj
├── src
│   └── bob.clj
└── test
    └── bob_test.clj
```

```diff
diff --git a/bob/project.clj b/bob/project.clj
index 803ad74..a21fc23 100644
--- a/bob/project.clj
+++ b/bob/project.clj
@@ -1,6 +1,4 @@
 (defproject bob "0.1.0-SNAPSHOT"
   :description "bob exercise."
   :url "https://github.com/exercism/xclojure/tree/master/bob"
-  :source-paths [""]
-  :test-paths [""]
   :dependencies [[org.clojure/clojure "1.7.0"]])
```

**Comment by kytrinyx** [comment]
+1 for using real-world conventions. Java has done this really well also.

The documentation should all be in this repository, inside the `docs/` directory, which should make it easier to clean that up.

**Comment by haus** [comment]
+1 to this idea. when I first started the clojure track the layout surprised me.

**Comment by yurrriq** [comment]
Done in #88.
